src/Entity/Lots.php
<?php

namespace App\Entity;

use App\Repository\LotsRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LotsRepository::class)
 */
class Lots
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $discription;

    /**
     * @ORM\Column(type="integer")
     */
    private $sold;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $seller_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(
     *     value=0,
     *     message="De prijs mag niet negatief zijn!"
     * )
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDiscription(): ?string
    {
        return $this->discription;
    }

    public function setDiscription(string $discription): self
    {
        $this->discription = $discription;

        return $this;
    }

    public function getSold(): ?int
    {
        return $this->sold;
    }

    public function setSold(int $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getSellerId(): ?User
    {
        return $this->seller_id;
    }

    public function setSellerId(?User $seller_id): self
    {
        $this->seller_id = $seller_id;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="integer")
     */
    private $Money;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getMoney(): ?int
    {
        return $this->Money;
    }

    public function setMoney(int $Money): self
    {
        $this->Money = $Money;

        return $this;
    }
}

src/Form/LotsType.php
<?php

namespace App\Form;

use App\Entity\Lots;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class LotsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('image', FileType::class, [
                'required' => true,
                'label' => 'foto\'s ',
                'mapped' => 'false',
                'constraints' => [
                    new File([
                        'maxSize' => '204800k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png'
                        ]
                        ,
                        'mimeTypesMessage' => 'Voer een geldig foto type in!',

                    ])
                ]
            ])
            ->add('title', TextType::class, ['label' => 'titel', 'required' => true,])
            ->add('discription', TextareaType::class, ['label' => 'beschrijving', 'required' => true])
            ->add('price', IntegerType::class, ['label' => 'prijs', 'required' => true,]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Lots::class,
        ]);
    }
}

src/Controller/LotsController.php
<?php

namespace App\Controller;

use App\Entity\Lots;
use App\Form\LotsType;
use App\Repository\LotsRepository;
use App\Repository\UserRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/")
 */
class LotsController extends AbstractController
{
//    renders main page
    /**
     * @Route("/", name="lots_index", methods={"GET"})
     */
    public function index(LotsRepository $lotsRepository): Response
    {
        return $this->render('lots/index.html.twig', [
            'lots' => $lotsRepository->findBy(['sold' => 0]),
        ]);
    }
//makes form and submit it
    /**
     * @Route("/new", name="lots_new", methods={"GET","POST"})
     */
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        $lot = new Lots();
        $form = $this->createForm(LotsType::class, $lot);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $lotImgFile = $form->get('image')->getData();

            $originalFilename = pathinfo($lotImgFile->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename . '-' . uniqid() . '.' . $lotImgFile->guessExtension();
            $lotImgFile->move(
                $this->getParameter('photo_directory'),
                $newFilename
            );
            $lot->setImage($this->getParameter('photo_directory') . $newFilename);
            $lot->setSold(0);
            $lot->setSellerId($this->getUser());
            $lot->setCreatedAt(new DateTime());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lot);
            $entityManager->flush();

            return $this->redirectToRoute('lots_index');
        }

        return $this->render('lots/new.html.twig', [
            'lot' => $lot,
            'form' => $form->createView(),
        ]);
    }

//removes lots if user requests
    /**
     * @Route("/{id}", name="lots_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Lots $lot): Response
    {
        if ($this->isCsrfTokenValid('delete' . $lot->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lot);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lots_index');
    }
// makes it possible to buy lots
    /**
     * @Route("/buy/{id}", name="lots_buy", methods={"GET","POST"})
     */
    public function buy(Request $request, Lots $lot, UserRepository $userRepository): Response
    {

        if ($this->getUser()->getMoney() >= $lot->getPrice()) {
            $this->getUser()->setMoney($this->getUser()->getMoney() - $lot->getPrice());
            $getMoney = $userRepository->findOneBy(['id' => $lot->getSellerId()->getId()]);
            $getMoney->setMoney($getMoney->getMoney() + $lot->getPrice());
            $lot->setSold(1);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lot);
            $entityManager->persist($getMoney);
            $entityManager->flush();
            $this->addFlash('succes', 'het product is gekocht!');
            return $this->redirectToRoute('lots_index');

        }
        $this->addFlash('notice', 'te weinig geld!');
        return $this->redirectToRoute('lots_index');

    }
}

templates/lots/_delete_form.html.twig
<form method="post" action="{{ path('lots_delete', {'id': lot.id}) }}" onsubmit="return confirm('weet u zeker dat u deze advertensie wilt verwijderen');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lot.id) }}">
    <button class="btn btn-primary ">Delete</button>
</form>

templates/lots/_form.html.twig
{% form_theme form 'lots/error.html.twig' %}
{{ form_start(form) }}
<br>
<div class="form-group">
    {{ form_errors(form.image) }}
    {{ form_label(form.image) }}
    <div class="custom-file">
        {{ form_widget(form.image, { 'attr': {'class': 'custom-file-input '}}) }}
        <label class="custom-file-label " for="lots_image">Selecteer bestand</label>
    </div>

    <br>
    {{ form_label(form.title) }}<br>
    {{ form_widget(form.title, { 'attr': {'class': 'form-control '}}) }}
    <br>
    {{ form_label(form.discription) }}<br>
    {{ form_widget(form.discription, { 'attr': {'class': 'form-control '}}) }}
    <br>
    {{ form_errors(form.price) }}
    {{ form_label(form.price) }}<br>
    {{ form_widget(form.price, { 'attr': {'class': 'form-control '}}) }}
    <br>
    <button class="btn btn-primary form-control">{{ button_label|default('plaatsen') }}</button>
</div>
{{ form_end(form) }}

templates/lots/error.html.twig
{% block form_errors %}
    {% for error in errors %}
        <div class="alert alert-danger" role="alert">
            {{ error.message }}
        </div>
    {% endfor %}
{% endblock %}

templates/lots/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recycle app|index{% endblock %}

{% block body %}
    {% for flashMessage in app.session.flashbag.get('succes') %}
        <div class="alert alert-success">
            {{ flashMessage }}
        </div>
    {% endfor %}
    {% for flashMessage in app.session.flashbag.get('notice') %}
        <div class="alert alert-danger">
            {{ flashMessage }}
        </div>
    {% endfor %}
    <div class="btn-group float-right">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            {{ app.user.email }}
        </button>
        <div class="dropdown-menu  ">
            <p class="dropdown-item">Portomonee: {{ app.user.money }}</p>
            <a class="dropdown-item" href="{{ path('lots_new') }}">plaats advertentie</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ path('app_logout') }}">uitloggen</a>
        </div>
    </div>
    <h1>Recycle app</h1>
    <h4 class="text-muted">Totaal legaal</h4>
    <div class="container mt-3">
        <div class="row">
            <div class="card-deck">
                {% for lot in lots %}
                    <div class="card mb-4 mx-auto" style="min-width: 18rem; max-width: 18rem;">
                        <img class="card-img-top h-50" src="{{ asset( lot.image) }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ lot.title }}</h5>
                            <p class="card-text">{{ lot.discription }}</p>
                            <div class="text-right">
                                {% if lot.price == 0 %}
                                    <p class="card-text">Gratis!</p>
                                {% else %}
                                    <p class="card-text">Prijs: {{ lot.price }}</p>
                                {% endif %}
                                {% if app.user.id == lot.sellerId.id %}
                                    {{ include('lots/_delete_form.html.twig') }}
                                {% else %}
                                    <a href="{{ path('lots_buy', {'id': lot.id}) }} }}" class="btn btn-primary">Koop</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% else %}
                    <tr>
                        <td colspan="8">geen advertentie</td>
                    </tr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/lots/new.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('CSS/file.css') }}">
{% endblock %}
{% block title %}Recycle-app|nieuwe advertentie{% endblock %}

{% block body %}
    <div class="center mx-auto mt-5 mb-5 text-justify w-25 p-2 ">
        <h1>nieuwe advertentie</h1>

        {{ include('lots/_form.html.twig') }}
        <div style="text-align: center">
            <a href="{{ path('lots_index') }}">annuleren</a>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function (e) {
            var fileName = document.getElementById("lots_image").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })

    </script>
{% endblock %}